### ISSUE TITLE
No access to ee repository

### ISSUE THREAD

**Issue by pschalk** [camunda/camunda-bpm-custom-batch#19]
Hi,

currently the travis build fails because I've an example which uses the ee version of the cockpit. 
(No worries, there is no checked in license file) 

It looks like that the project is not correctly configured to have access to the ee repository.
How can we fix this? 

Cheers,
Patrick

**Comment by pschalk** [comment]
Or maybe @menski has some idea how to fix this?

**Comment by hawky-4s-** [comment]
The problem is we do not offer EE repo access to community extensions. Maybe excluding the example from the maven build and just linking it in the docs might make more sense?

**Comment by pschalk** [comment]
Ok, would also be ok, I just did it, thanks!
