### ISSUE TITLE
CustomBatchBuilder.calculateTotalJobs() uses Integer division

### ISSUE THREAD

**Issue by tobiasbehr** [camunda/camunda-bpm-custom-batch#9]
`  private int calculateTotalJobs() {
    return Integer.divideUnsigned(this.batchData.size(), this.batch.getInvocationsPerBatchJob());
  }`

When batchData.size() == 1500 and getInvocationsPerBatchJob() == 1000, then calculateTotalJobs returns 1 but should return 2.

**Comment by pschalk** [comment]
Many thanks, merged your pull request.
